apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: grafana-loki
spec:
  #chart:
  #  repository: https://grafana.github.io/loki/charts
  #  name: "loki/loki-stack"
  chart:
    git: https://github.com/grafana/loki
    path: production/helm/loki-stack
    ref: master
  values:
    loki:
      enabled: true
    promtail:
      enabled: true
    fluent-bit:
      enabled: false
    grafana:
      enabled: false
    prometheus:
      enabled: false
