apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: echo-api
  namespace: core
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: semver:~2
spec:
  chart:
    ref: master
  values:
    replicaCount: 3
