{{- if .Values.hpa.enabled -}}
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "api.name" . }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "api.name" . }}
  minReplicas: {{ .Values.replicaCount }}
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  metrics:
  {{- if .Values.hpa.cpu }}
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.hpa.cpu }}
  {{- end }}
  {{- if .Values.hpa.memory }}
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{ .Values.hpa.memory }}
  {{- end }}
  {{- if .Values.hpa.http_requests_sec }}
  - type: Pods
    pods:
      metric:
        name: echo_http_requests_per_second
      target:
        type: AverageValue
        averageValue: {{ .Values.hpa.http_requests_sec }}
  {{- end }}
  {{- if .Values.hpa.http_request_duration_seconds_avg }}
  - type: Pods
    pods:
      metric:
        name: echo_http_request_duration_seconds_avg
      target:
        type: AverageValue
        averageValue: {{ .Values.hpa.http_request_duration_seconds_avg }}
  {{- end }}
  {{- if .Values.hpa.dev_digestor_lag }}
  - type: External
    external:
      metric:
        name: dev_digestor_lag
      target:
        type: Value
        value: {{ .Values.hpa.dev_digestor_lag }}
  {{- end }}
{{- end }}
