{{- if .Values.secrets -}}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: {{ template "api.name" . }}
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
spec:
  encryptedData:
    {{- range $key, $value := .Values.secrets }}
    {{ $key }}: {{ $value }}
    {{- end }}
  template:
    metadata:
      creationTimestamp: null
      name: {{ template "api.fullname" . }}
      namespace: {{ .Release.Namespace }}
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
{{- end}}
