apiVersion: v1
kind: Service
metadata:
  name: {{ include "api.name" . }}
  labels: {{ include "api.labels" . | nindent 4 }}
{{- if .Values.service.annotations }}
  annotations:
    {{- range $key, $value := .Values.service.annotations }}
    {{ $key }}: {{ $value }}
    {{- end }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: http
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.servicePort }}
    protocol: TCP
  selector:
    app: {{ include "api.name" . }}
    instance: {{ .Release.Name }}
