apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: echo-api
  namespace: core
  annotations:
    flux.weave.works/automated: "false"
spec:
  chart:
    ref: master
  values:
    image:
      tag: 2.2
    replicaCount: 2
