---
replicaCount: 1

image:
  repository: repository/image
  tag: 1.0.0
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

deployment:
  antiaffinity:
    enabled: false

livenessProbe: {}

readinessProbe: {}

ports:
- name: http
  containerPort: 8080
  protocol: TCP

service:
  type: ClusterIP
  port: 80
  sslport: 443
  annotations: {}

servicePort: http

ingress:
  enabled: false

prometheus:
  enabled: true

annotations: {}

labels: {}

resources: {}

hpa:
  enabled: false

env: {}

addEnv: {}

config: {}

configPath: /config/
configFilename: config.yaml

secrets: {}

certs: {}

certsMountPath: /app/secrets/
certsMountSubPath: {}

nodeSelector: {}

tolerations: []

affinity: {}
